
POST http://localhost:4001/api/auth/register
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Perez",
    "email": "juan.perez@example.com",
    "password": "password123",
    "tipo": "administrador",
    "direccion": "Calle Falsa 123",
    "ciudad": "Lima",
    "telefono": "999999999"
}

####
POST http://localhost:4001/api/auth/register
Content-Type: application/json

{
    "nombre": "Pepe",
    "apellido": "Perez",
    "email": "juan.pepe@example.com",
    "password": "password123",
    "tipo": "cliente",
    "direccion": "Calle Falsa 123",
    "ciudad": "Lima",
    "telefono": "999999999"
}
####
POST http://localhost:4001/api/auth/login
Content-Type: application/json

{
    "email": "juan.pepe@example.com",
    "password": "password123"
}
####
POST http://localhost:4001/api/auth/login
Content-Type: application/json

{
    "email": "juan.perez@example.com",
    "password": "password123"
}

####
GET http://localhost:4001/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwidGlwbyI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4OTM1MTcsImV4cCI6MTczMjg5NzExN30.PE_rWIr9W7VMl7-SbAqOqrF0j8r0fCkmxEt1dia4Ers
####
PUT http://localhost:4001/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwidGlwbyI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4OTM1MTcsImV4cCI6MTczMjg5NzExN30.PE_rWIr9W7VMl7-SbAqOqrF0j8r0fCkmxEt1dia4Ers

{
    "nombre": "Juan Actualizado",
    "apellido": "Perez Actualizado",
    "email": "juan.actualizado@example.com",
    "password": "newpassword123",
    "direccion": "Avenida Siempre Viva 456",
    "ciudad": "Arequipa",
    "telefono": "998888888"
}

####
DELETE http://localhost:4001/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwidGlwbyI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4OTM1MTcsImV4cCI6MTczMjg5NzExN30.PE_rWIr9W7VMl7-SbAqOqrF0j8r0fCkmxEt1dia4Ers


####
GET http://localhost:4001/api/products
####
GET http://localhost:4001/api/products?nombre=Producto1
####
GET http://localhost:4001/api/products/1
####
POST http://localhost:4001/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwidGlwbyI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4OTUzOTUsImV4cCI6MTczMjg5ODk5NX0.ZuZSqYNaKdSS6VAuo4lKbNo-CwX09cUWgIdMJL6U_LI

{
    "nombre": "Producto Nuevo",
    "descripcion": "Descripción del nuevo producto",
    "marca": "Marca Nueva",
    "precio": 100.50,
    "stock": 20,
    "imagen": "http://example.com/image.jpg"
}
####
PUT http://localhost:4001/api/products/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqdWFuLnBlcGVAZXhhbXBsZS5jb20iLCJ0aXBvIjoiY2xpZW50ZSIsImlhdCI6MTczMjg5Mzc0MywiZXhwIjoxNzMyODk3MzQzfQ.SvcwOtPDSg1AviOdTqW93OCyIyDrcB4ZqMoBDltJ1lI.eyJpZCI6MiwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwidGlwbyI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4OTM2MTcsImV4cCI6MTczMjg5NzIxN30.ZGqbc-gK6D7EYpSfE9rQ2APYReycJVP2ui1ThNKTpvA

{
    "nombre": "Producto Actualizado",
    "descripcion": "Descripción actualizada",
    "marca": "Marca Actualizada",
    "precio": 120.00,
    "stock": 15,
    "imagen": "http://example.com/image_updated.jpg"
}
####
DELETE http://localhost:4001/api/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwidGlwbyI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4OTM2MTcsImV4cCI6MTczMjg5NzIxN30.ZGqbc-gK6D7EYpSfE9rQ2APYReycJVP2ui1ThNKTpvA
####
GET http://localhost:4001/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqdWFuLnBlcGVAZXhhbXBsZS5jb20iLCJ0aXBvIjoiY2xpZW50ZSIsImlhdCI6MTczMjg5NDQ4NCwiZXhwIjoxNzMyODk4MDg0fQ.WHzZlzuuQK1w3D0jrP3CYBuN7rwYffGoTpPWCOGsqbE
####
POST http://localhost:4001/api/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqdWFuLnBlcGVAZXhhbXBsZS5jb20iLCJ0aXBvIjoiY2xpZW50ZSIsImlhdCI6MTczMjg5NTQ3NCwiZXhwIjoxNzMyODk5MDc0fQ.ZIf628Cv1s5VL1hOAYEjlkZzV2j6qwXBR7aGVki_YL0

{
    "productId": 2,
    "cantidad": 2
}
####
PUT http://localhost:4001/api/cart/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqdWFuLnBlcGVAZXhhbXBsZS5jb20iLCJ0aXBvIjoiY2xpZW50ZSIsImlhdCI6MTczMjg5NTQ3NCwiZXhwIjoxNzMyODk5MDc0fQ.ZIf628Cv1s5VL1hOAYEjlkZzV2j6qwXBR7aGVki_YL0

{
    "cantidad": 5
}
####
DELETE http://localhost:4001/api/cart/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqdWFuLnBlcGVAZXhhbXBsZS5jb20iLCJ0aXBvIjoiY2xpZW50ZSIsImlhdCI6MTczMjg5NTQ3NCwiZXhwIjoxNzMyODk5MDc0fQ.ZIf628Cv1s5VL1hOAYEjlkZzV2j6qwXBR7aGVki_YL0
####
DELETE http://localhost:4001/api/cart
Authorization: Bearer <TOKEN>
####
GET http://localhost:4001/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqdWFuLnBlcGVAZXhhbXBsZS5jb20iLCJ0aXBvIjoiY2xpZW50ZSIsImlhdCI6MTczMjg5NTQ3NCwiZXhwIjoxNzMyODk5MDc0fQ.ZIf628Cv1s5VL1hOAYEjlkZzV2j6qwXBR7aGVki_YL0
####
GET http://localhost:4001/api/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqdWFuLnBlcGVAZXhhbXBsZS5jb20iLCJ0aXBvIjoiY2xpZW50ZSIsImlhdCI6MTczMjg5NTQ3NCwiZXhwIjoxNzMyODk5MDc0fQ.ZIf628Cv1s5VL1hOAYEjlkZzV2j6qwXBR7aGVki_YL0
####
POST http://localhost:4001/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqdWFuLnBlcGVAZXhhbXBsZS5jb20iLCJ0aXBvIjoiY2xpZW50ZSIsImlhdCI6MTczMjg5NTQ3NCwiZXhwIjoxNzMyODk5MDc0fQ.ZIf628Cv1s5VL1hOAYEjlkZzV2j6qwXBR7aGVki_YL0

{
    "items": [
        {
            "idProducto": 2,
            "cantidad": 2,
            "precio": 100.50
        }
    ],
    "total": 201.00,
    "subTotal": 190.00,
    "metodoDeEntrega": "delivery",
    "nroTarjeta": "1234567890123456",
    "tipoTarjeta": "Visa",
    "fecha": "2024-11-30T00:00:00Z"
}
####
GET http://localhost:4001/api/admin/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwidGlwbyI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4OTc4MDQsImV4cCI6MTczMjkwMTQwNH0.DloKxI2qxuHejxH2S8zEVxy1EQzytao3N-pYrGyLNGE
####
GET http://localhost:4001/api/admin/orders/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwidGlwbyI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4OTc4MDQsImV4cCI6MTczMjkwMTQwNH0.DloKxI2qxuHejxH2S8zEVxy1EQzytao3N-pYrGyLNGE
####
GET http://localhost:4001/api/admin/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwidGlwbyI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4OTc4MDQsImV4cCI6MTczMjkwMTQwNH0.DloKxI2qxuHejxH2S8zEVxy1EQzytao3N-pYrGyLNGE
####
POST http://localhost:4001/api/admin/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwidGlwbyI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4OTc4MDQsImV4cCI6MTczMjkwMTQwNH0.DloKxI2qxuHejxH2S8zEVxy1EQzytao3N-pYrGyLNGE

{
    "nombre": "Producto Admin3",
    "descripcion": "Producto creado por admin",
    "marca": "Marca Admin",
    "precio": 200.00,
    "stock": 10,
    "imagen": "http://example.com/admin_product.jpg"
}
####
PUT http://localhost:4001/api/admin/products/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwidGlwbyI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4OTc4MDQsImV4cCI6MTczMjkwMTQwNH0.DloKxI2qxuHejxH2S8zEVxy1EQzytao3N-pYrGyLNGE

{
    "nombre": "Producto Admin Actualizado",
    "descripcion": "Descripción actualizada",
    "marca": "Marca Actualizada",
    "precio": 250.00,
    "stock": 5
}
####
DELETE http://localhost:4001/api/admin/products/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwidGlwbyI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4OTc4MDQsImV4cCI6MTczMjkwMTQwNH0.DloKxI2qxuHejxH2S8zEVxy1EQzytao3N-pYrGyLNGE
